spring:
  application:
    name: stock-analytics-backend

  datasource:
    url: jdbc:sqlite:./database/stock-analytics.db
    driver-class-name: org.sqlite.JDBC

server:
  port: 8080

http:
  client:
    connect-timeout-seconds: 5
    response-timeout-seconds: 10

market-data:
  provider-order:
    instrument-search:
      - yahoo
      - twelve-data
      - alpha-vantage
      - dummy-fallback

  providers:
    yahoo:
      enabled: true
      base-url: https://query1.finance.yahoo.com
      timeout-seconds: 10

    twelve-data:
      enabled: false
      base-url: https://api.twelvedata.com
      api-key: ${TWELVE_DATA_API_KEY:}

    alpha-vantage:
      enabled: false
      base-url: https://www.alphavantage.co
      api-key: ${ALPHA_VANTAGE_API_KEY:}

    dummy-primary:
      enabled: false

    dummy-fallback:
      enabled: true

search:
  preference:
    default-exchange-score: 0
    exchange-preference-scores:
      NSE: 20
      BSE: 18
      NYSE: 8
      NASDAQ: 8
      LSE: 6
      FRANKFURT: 4
      
logging:
  level:
    root: INFO
    com.stockanalytics: DEBUG